---
engines:
  duplication:
    exclude_paths:
      - "pysm/serialization.py"
    minTokenMatch: 120
  metric:
    exclude_paths:
      - "pysm/serialization.py"
exclude_paths:
  - ".codacy.yml"
  - ".github/**"
  - ".gitignore"
  - ".pylintrc"
  - "conftest.py"
  - "docs/**"
  - "examples/**"
  - "LICENSE"
  - "README.rst"
  - "setup.cfg"
  - "setup.py"
  - "test/**"
