---
engines:
  duplication:
    exclude_paths:
      - "pysm/serialization.py"
    minTokenMatch: 120
  metric:
    exclude_paths:
      - "pysm/serialization.py"
exclude_paths:
  - "*"
  - "**/*"
include_paths:
  - "pysm/**"
