import logging
from typing import (
    Any,
    Callable,
    DefaultDict,
    Dict,
    Hashable,
    Iterable,
    List,
    Optional,
    Set,
    Tuple,
)

_Callback = Callable[[Any, Any], Any]
_Transition = Dict[str, Any]
_TransitionKey = Tuple[Optional[State], Hashable, Optional[Hashable]]

class AnyEvent(object): ...
any_event: AnyEvent
logger: logging.Logger

class StateMachineException(Exception): ...

class Event(object):
    name: Hashable
    input: Optional[Hashable]
    propagate: bool
    cargo: Dict[str, Any]
    state_machine: Optional[StateMachine]
    def __init__(self, name: Hashable, input: Optional[Hashable] = ...,
                 **cargo: Any) -> None: ...
    def __repr__(self) -> str: ...

class State(object):
    parent: Optional[StateMachine]
    name: str
    handlers: Dict[Hashable, _Callback]
    initial: bool
    def __init__(self, name: str) -> None: ...
    def __repr__(self) -> str: ...
    def register_handlers(self) -> None: ...
    def is_substate(self, state: State) -> bool: ...
    def _on(self, event: Event) -> None: ...
    def _nop(self, state: State, event: Event) -> bool: ...

class TransitionsContainer(object):
    _machine: StateMachine
    _transitions: DefaultDict[_TransitionKey, List[_Transition]]
    def __init__(self, machine: StateMachine) -> None: ...
    def add(self, key: _TransitionKey, transition: _Transition) -> None: ...
    def get(self, event: Event) -> Optional[_Transition]: ...
    def _get_transition_matching_condition(
        self,
        key: _TransitionKey,
        event: Event,
    ) -> Optional[_Transition]: ...

class Stack(object):
    deque: Any
    def __init__(self, maxlen: Optional[int] = ...) -> None: ...
    def pop(self) -> Any: ...
    def push(self, value: Any) -> None: ...
    def peek(self) -> Any: ...
    def __repr__(self) -> str: ...

class StateMachine(State):
    STACK_SIZE: int
    states: Set[State]
    state: Optional[State]
    _transitions: TransitionsContainer
    _leaf_state: Optional[State]
    state_stack: Stack
    leaf_state_stack: Stack
    stack: Stack
    def __init__(self, name: str) -> None: ...
    def add_state(self, state: State, initial: bool = ...) -> None: ...
    def add_states(self, *states: State) -> None: ...
    def set_initial_state(self, state: State) -> None: ...
    @property
    def initial_state(self) -> Optional[State]: ...
    @property
    def root_machine(self) -> StateMachine: ...
    def add_transition(
        self,
        from_state: State,
        to_state: Optional[State],
        events: Iterable[Hashable],
        input: Optional[Iterable[Hashable]] = ...,
        action: Optional[_Callback] = ...,
        condition: Optional[_Callback] = ...,
        before: Optional[_Callback] = ...,
        after: Optional[_Callback] = ...,
    ) -> None: ...
    @property
    def leaf_state(self) -> State: ...
    def _get_leaf_state(self, state: State) -> State: ...
    def _get_transition(self, event: Event) -> Optional[_Transition]: ...
    def _exit_states(
        self,
        event: Optional[Event],
        from_state: State,
        to_state: Optional[State],
    ) -> Optional[State]: ...
    def _enter_states(
        self,
        event: Optional[Event],
        top_state: Optional[State],
        to_state: Optional[State],
    ) -> None: ...
    def initialize(self) -> None: ...
    def dispatch(self, event: Event) -> None: ...
    def set_previous_leaf_state(self, event: Optional[Event] = ...) -> None: ...
    def revert_to_previous_leaf_state(self, event: Optional[Event] = ...) -> None: ...

class Validator(object):
    state_machine: StateMachine
    template: str
    def __init__(self, state_machine: StateMachine) -> None: ...
    def _raise(self, msg: str) -> None: ...
    def validate_add_state(self, state: Any, initial: bool) -> None: ...
    def _validate_state_already_added(self, state: State) -> None: ...
    def validate_set_initial(self, state: State) -> None: ...
    def validate_add_transition(
        self,
        from_state: State,
        to_state: Optional[State],
        events: Iterable[Hashable],
        input: Iterable[Hashable],
    ) -> None: ...
    def _validate_from_state(self, from_state: State) -> None: ...
    def _validate_to_state(self, to_state: Optional[State]) -> None: ...
    def _validate_events(self, events: Any) -> None: ...
    def _validate_input(self, input: Any) -> None: ...
    def validate_initial_state(self, machine: StateMachine) -> None: ...

def is_iterable(obj: Any) -> bool: ...
def patch_deque(deque_module: Any) -> Any: ...
