from typing import Any, Callable, Dict, Hashable, Iterable, Optional

_Callback = Callable[[Any, Any], Any]
_Transition = Dict[str, Any]

class AnyEvent(object): ...
any_event: AnyEvent
logger: Any

class StateMachineException(Exception): ...

class Event(object):
    name: Hashable
    input: Optional[Hashable]
    propagate: bool
    cargo: Dict[str, Any]
    state_machine: Any
    def __init__(self, name: Hashable, input: Optional[Hashable] = ...,
                 **cargo: Any) -> None: ...

class State(object):
    parent: Optional[StateMachine]
    name: str
    handlers: Dict[Hashable, _Callback]
    initial: bool
    def __init__(self, name: str) -> None: ...
    def register_handlers(self) -> None: ...
    def is_substate(self, state: State) -> bool: ...

class Stack(object):
    deque: Any
    def __init__(self, maxlen: Optional[int] = ...) -> None: ...
    def pop(self) -> Any: ...
    def push(self, value: Any) -> None: ...
    def peek(self) -> Any: ...

class StateMachine(State):
    STACK_SIZE: int
    states: Any
    state: Optional[State]
    _transitions: Any
    _leaf_state: Optional[State]
    state_stack: Stack
    leaf_state_stack: Stack
    stack: Stack
    def __init__(self, name: str) -> None: ...
    def add_state(self, state: State, initial: bool = ...) -> None: ...
    def add_states(self, *states: State) -> None: ...
    def set_initial_state(self, state: State) -> None: ...
    @property
    def initial_state(self) -> Optional[State]: ...
    @property
    def root_machine(self) -> StateMachine: ...
    def add_transition(
        self,
        from_state: State,
        to_state: Optional[State],
        events: Iterable[Hashable],
        input: Optional[Iterable[Hashable]] = ...,
        action: Optional[_Callback] = ...,
        condition: Optional[_Callback] = ...,
        before: Optional[_Callback] = ...,
        after: Optional[_Callback] = ...,
    ) -> None: ...
    @property
    def leaf_state(self) -> State: ...
    def _get_leaf_state(self, state: State) -> State: ...
    def _get_transition(self, event: Event) -> Optional[_Transition]: ...
    def _exit_states(
        self,
        event: Optional[Event],
        from_state: State,
        to_state: Optional[State],
    ) -> Optional[State]: ...
    def _enter_states(
        self,
        event: Optional[Event],
        top_state: Optional[State],
        to_state: Optional[State],
    ) -> None: ...
    def initialize(self) -> None: ...
    def dispatch(self, event: Event) -> None: ...
    def set_previous_leaf_state(self, event: Optional[Event] = ...) -> None: ...
    def revert_to_previous_leaf_state(self, event: Optional[Event] = ...) -> None: ...

def is_iterable(obj: Any) -> bool: ...
def patch_deque(deque_module: Any) -> Any: ...
